// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/posts/header', 'views/author/posts/post', 'models/author/posts/post'], function(PageView, JST, FooterView, HeaderView, PostView, PostModel) {
  'use strict';
  var BlogAboutPageView, _ref;
  return BlogAboutPageView = (function(_super) {
    __extends(BlogAboutPageView, _super);

    function BlogAboutPageView() {
      _ref = BlogAboutPageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BlogAboutPageView.prototype.className = 'aboutPage';

    BlogAboutPageView.prototype.regions = {
      '#post': 'post',
      'footer': 'footer',
      'header': 'header'
    };

    BlogAboutPageView.prototype.templateName = 'blog_about_page';

    BlogAboutPageView.prototype.render = function() {
      var fv, hv;
      BlogAboutPageView.__super__.render.apply(this, arguments);
      hv = new HeaderView();
      fv = new FooterView();
      return pressFooter();
    };

    return BlogAboutPageView;

  })(PageView);
});
