// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var AdminStoriesPostModel, _ref;
  return AdminStoriesPostModel = (function(_super) {
    __extends(AdminStoriesPostModel, _super);

    function AdminStoriesPostModel() {
      _ref = AdminStoriesPostModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminStoriesPostModel.prototype.name = 'AdminStoriesPost';

    AdminStoriesPostModel.prototype.assignAsDayStory = function(callback) {
      this.method = 'GET';
      this.url = function() {
        return 'api/post/set_daystory/' + this.data.id;
      };
      return this.request(callback, true);
    };

    AdminStoriesPostModel.prototype.addLikes = function(likes, callback) {
      this.method = 'POST';
      this.url = function() {
        return 'api/post/add_likes/' + this.data.id;
      };
      this.requestData = {
        likes: likes
      };
      return this.request(callback, true);
    };

    return AdminStoriesPostModel;

  })(Model);
});
