// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/admin/stories/post'], function(Queue, PostModel) {
  'use strict';
  var AdminStoriesPostQueueModel, _ref;
  return AdminStoriesPostQueueModel = (function(_super) {
    __extends(AdminStoriesPostQueueModel, _super);

    function AdminStoriesPostQueueModel() {
      _ref = AdminStoriesPostQueueModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminStoriesPostQueueModel.prototype.name = 'AdminStoriesPostQueue';

    AdminStoriesPostQueueModel.prototype.elementName = 'AdminStoriesPost';

    AdminStoriesPostQueueModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/post/get_all_last_week';
      };
      this.method = 'GET';
      return AdminStoriesPostQueueModel.__super__.load.call(this, callback);
    };

    AdminStoriesPostQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new PostModel();
      model.data = elData;
      return model;
    };

    return AdminStoriesPostQueueModel;

  })(Queue);
});
