// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST', 'categories'], function(EditableView, JST, categories) {
  'use strict';
  var AuthorPostsNewBlankCaptionView;
  return AuthorPostsNewBlankCaptionView = (function(_super) {

    __extends(AuthorPostsNewBlankCaptionView, _super);

    function AuthorPostsNewBlankCaptionView() {
      return AuthorPostsNewBlankCaptionView.__super__.constructor.apply(this, arguments);
    }

    AuthorPostsNewBlankCaptionView.prototype.className = 'interview';

    AuthorPostsNewBlankCaptionView.prototype.tagName = 'article';

    AuthorPostsNewBlankCaptionView.prototype.templateName = 'author_posts_new_blank_caption';

    AuthorPostsNewBlankCaptionView.prototype.modes = ['passive', 'active'];

    AuthorPostsNewBlankCaptionView.prototype.getTemplateData = function() {
      var cat, cats, key;
      cats = {};
      for (key in categories) {
        cat = categories[key];
        if (key > 0) {
          cats[key] = cat;
        }
      }
      return {
        categories: cats
      };
    };

    return AuthorPostsNewBlankCaptionView;

  })(EditableView);
});
