// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/author/posts/new/blank/question'], function(QueueView, JST, QuestionView) {
  'use strict';
  var AuthorPostsNewBlankQuestionQueueView, _ref;
  return AuthorPostsNewBlankQuestionQueueView = (function(_super) {
    __extends(AuthorPostsNewBlankQuestionQueueView, _super);

    function AuthorPostsNewBlankQuestionQueueView() {
      _ref = AuthorPostsNewBlankQuestionQueueView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AuthorPostsNewBlankQuestionQueueView.prototype.className = 'authorPostsNewBlankQuestionQueue';

    AuthorPostsNewBlankQuestionQueueView.prototype.templateName = 'author_posts_new_blank_question_queue';

    AuthorPostsNewBlankQuestionQueueView.prototype.sortable = true;

    AuthorPostsNewBlankQuestionQueueView.prototype.createElementView = function(model) {
      return new QuestionView({
        model: model
      });
    };

    return AuthorPostsNewBlankQuestionQueueView;

  })(QueueView);
});
