// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AuthorPostsNewBlankQuesionView;
  return AuthorPostsNewBlankQuesionView = (function(_super) {

    __extends(AuthorPostsNewBlankQuesionView, _super);

    function AuthorPostsNewBlankQuesionView() {
      return AuthorPostsNewBlankQuesionView.__super__.constructor.apply(this, arguments);
    }

    AuthorPostsNewBlankQuesionView.prototype.className = 'question';

    AuthorPostsNewBlankQuesionView.prototype.tagName = 'article';

    AuthorPostsNewBlankQuesionView.prototype.templateName = 'author_posts_new_blank_question';

    AuthorPostsNewBlankQuesionView.prototype.modes = ['passive', 'active', 'button'];

    AuthorPostsNewBlankQuesionView.prototype.addCallback = function() {
      return this.setMode('button');
    };

    AuthorPostsNewBlankQuesionView.prototype.updateCallback = function() {
      return this.setMode('passive');
    };

    return AuthorPostsNewBlankQuesionView;

  })(EditableView);
});
