// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST', 'chaplin'], function(View, JST, Chaplin) {
  'use strict';
  var IndexDaystoryView, _ref;
  return IndexDaystoryView = (function(_super) {
    __extends(IndexDaystoryView, _super);

    function IndexDaystoryView() {
      _ref = IndexDaystoryView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    IndexDaystoryView.prototype.className = 'daystory';

    IndexDaystoryView.prototype.templateName = 'index_daystory';

    IndexDaystoryView.prototype.initialize = function() {
      IndexDaystoryView.__super__.initialize.apply(this, arguments);
      return Chaplin.mediator.subscribe('onLogout', this.softRender());
    };

    IndexDaystoryView.prototype.softRender = function() {
      return IndexDaystoryView.__super__.softRender.apply(this, arguments);
    };

    return IndexDaystoryView;

  })(View);
});
