// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST'], function(PageView, JST) {
  'use strict';
  var e404PageView, _ref;
  return e404PageView = (function(_super) {
    __extends(e404PageView, _super);

    function e404PageView() {
      _ref = e404PageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    e404PageView.prototype.className = 'indexPage';

    e404PageView.prototype.templateName = 'e404page';

    return e404PageView;

  })(PageView);
});
