// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/admin/header', 'models/admin/timeline/postQueue', 'views/admin/timeline/postQueue'], function(PageView, JST, FooterView, HeaderView, TimelinePostQueueModel, TimelinePostQueueView) {
  'use strict';
  var AdminTimelinePageView, _ref;
  return AdminTimelinePageView = (function(_super) {
    __extends(AdminTimelinePageView, _super);

    function AdminTimelinePageView() {
      _ref = AdminTimelinePageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminTimelinePageView.prototype.className = 'timelinePage';

    AdminTimelinePageView.prototype.regions = {
      '#queue': 'queue',
      'footer': 'footer',
      'header': 'header'
    };

    AdminTimelinePageView.prototype.templateName = 'timeline_page';

    AdminTimelinePageView.prototype.initialize = function() {
      return AdminTimelinePageView.__super__.initialize.apply(this, arguments);
    };

    AdminTimelinePageView.prototype.render = function() {
      var tq,
        _this = this;
      AdminTimelinePageView.__super__.render.apply(this, arguments);
      new HeaderView();
      new FooterView();
      tq = new TimelinePostQueueModel();
      return tq.load(function() {
        var tqView;
        tqView = new TimelinePostQueueView({
          model: tq
        });
        return tqView.setRegion('queue').render();
      });
    };

    return AdminTimelinePageView;

  })(PageView);
});
