// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var AdminTimelinePostView, _ref;
  return AdminTimelinePostView = (function(_super) {
    __extends(AdminTimelinePostView, _super);

    function AdminTimelinePostView() {
      _ref = AdminTimelinePostView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminTimelinePostView.prototype.className = 'element';

    AdminTimelinePostView.prototype.templateName = 'admin_timeline_post';

    AdminTimelinePostView.prototype.events = {
      'click': function(e) {
        var $target,
          _this = this;
        $target = $(e.target);
        if ($target.attr('data-check-button') != null) {
          return this.model.setChecked(function() {
            return $target.parent().parent().hide();
          });
        }
      }
    };

    return AdminTimelinePostView;

  })(View);
});
