// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/people/explore/post'], function(Queue, PostModel) {
  'use strict';
  var PeopleExplorePostSearchModel, _ref;
  return PeopleExplorePostSearchModel = (function(_super) {
    __extends(PeopleExplorePostSearchModel, _super);

    function PeopleExplorePostSearchModel() {
      _ref = PeopleExplorePostSearchModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PeopleExplorePostSearchModel.prototype.name = 'PeopleExplorePostQueue';

    PeopleExplorePostSearchModel.prototype.elementName = 'PeopleExplorePost';

    PeopleExplorePostSearchModel.prototype.initialize = function(params) {
      PeopleExplorePostSearchModel.__super__.initialize.call(this, params);
      this.text = params.text;
      return this.mode = params.mode;
    };

    PeopleExplorePostSearchModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/people/search_post_by_' + this.mode + '/' + this.text;
      };
      this.method = 'GET';
      return PeopleExplorePostSearchModel.__super__.load.call(this, callback);
    };

    PeopleExplorePostSearchModel.prototype.createElementModel = function(elData) {
      var model;
      model = new PostModel();
      model.data = elData;
      return model;
    };

    return PeopleExplorePostSearchModel;

  })(Queue);
});
