// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/pagingQueue', 'models/timeline/post'], function(PagingQueue, PostModel) {
  'use strict';
  var TimelinePostQueueModel, _ref;
  return TimelinePostQueueModel = (function(_super) {
    __extends(TimelinePostQueueModel, _super);

    function TimelinePostQueueModel() {
      _ref = TimelinePostQueueModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TimelinePostQueueModel.prototype.name = 'TimelinePostQueue';

    TimelinePostQueueModel.prototype.elementName = 'TimelinePost';

    TimelinePostQueueModel.prototype.paging = true;

    TimelinePostQueueModel.prototype.stackUrl = function() {
      return 'api/friends/timeline_stack';
    };

    TimelinePostQueueModel.prototype.loadUrl = function() {
      return 'api/friends/timeline';
    };

    TimelinePostQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new PostModel();
      model.data = elData;
      return model;
    };

    return TimelinePostQueueModel;

  })(PagingQueue);
});
