// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/timeline/post'], function(Queue, PostModel) {
  'use strict';
  var TimelinePostQueueModel;
  return TimelinePostQueueModel = (function(_super) {

    __extends(TimelinePostQueueModel, _super);

    function TimelinePostQueueModel() {
      return TimelinePostQueueModel.__super__.constructor.apply(this, arguments);
    }

    TimelinePostQueueModel.prototype.name = 'TimelinePostQueue';

    TimelinePostQueueModel.prototype.elementName = 'TimelinePost';

    TimelinePostQueueModel.prototype.paging = true;

    TimelinePostQueueModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/friends/timeline/' + this.offset;
      };
      this.method = 'GET';
      return TimelinePostQueueModel.__super__.load.call(this, callback);
    };

    TimelinePostQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new PostModel();
      model.data = elData;
      return model;
    };

    return TimelinePostQueueModel;

  })(Queue);
});
