// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var EditableView;
  return EditableView = (function(_super) {

    __extends(EditableView, _super);

    function EditableView() {
      return EditableView.__super__.constructor.apply(this, arguments);
    }

    EditableView.prototype.autoRender = false;

    EditableView.prototype.events = {
      'click': function(e) {
        var $target;
        $target = $(e.target);
        if ($target.attr('data-to-mode') != null) {
          this.setMode($target.attr('data-to-mode'));
        }
        if ($target.attr('data-send-button') != null) {
          this.send();
        }
        if ($target.attr('data-delete-button') != null) {
          return this.del();
        }
      },
      'keyup': function(e) {
        var $target;
        $target = $(e.target);
        if ($target.attr('data-field') != null) {
          return this.model.data[$target.attr('data-field')] = $target.val();
        }
      }
    };

    EditableView.prototype.send = function() {
      if (this.model.data.id != null) {
        return this.update();
      } else {
        return this.add();
      }
    };

    EditableView.prototype.add = function() {
      var _this = this;
      return this.model.add(function() {
        return _this.addCallback();
      });
    };

    EditableView.prototype.update = function() {
      var _this = this;
      return this.model.update(function() {
        return _this.setMode('passive');
      });
    };

    EditableView.prototype.del = function() {
      this.model["delete"]();
      return this.dispose();
    };

    EditableView.prototype.checkTemplate = function() {
      var mode, tempName, _i, _len, _ref, _results;
      _ref = this.modes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mode = _ref[_i];
        tempName = this.formatTemplateName(mode);
        if (JST[tempName] == null) {
          throw "no template with name " + tempName + " found";
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    EditableView.prototype.initialize = function() {
      EditableView.__super__.initialize.apply(this, arguments);
      this.regionSet = false;
      this.rendered = false;
      return this.modesHistory = [];
    };

    EditableView.prototype.getTemplateFunction = function() {
      return JST[this.currentTemplateName];
    };

    EditableView.prototype.setRegion = function(region) {
      this.region = region;
      this.regionSet = true;
      return this;
    };

    EditableView.prototype.softRender = function() {
      var tnBuffer;
      if (this.rendered) {
        return this.$el.html(JST[this.currentTemplateName](this.getTemplateData()));
      } else {
        tnBuffer = this.templateName;
        this.templateName = this.currentTemplateName;
        this.render();
        this.templateName = tnBuffer;
        return this.rendered = true;
      }
    };

    EditableView.prototype.setMode = function(mode, callback) {
      var _ref;
      if (this.modes.indexOf(mode) === -1) {
        throw "no mode '" + mode + "' available";
      }
      this.currentTemplateName = this.formatTemplateName(mode);
      this.softRender();
      if ((_ref = this.mode) != null ? _ref : this.mode = mode) {
        this.modesHistory.push(this.mode);
      }
      if (typeof callback === "function") {
        callback();
      }
      return this;
    };

    EditableView.prototype.formatTemplateName = function(mode) {
      return "" + (this.templateName + '_' + mode);
    };

    EditableView.prototype.setPreviousMode = function() {
      return this.setMode(this.modesHistory[this.modesHistory.length - 1]);
    };

    return EditableView;

  })(View);
});
