// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue'], function(QueueView) {
  'use strict';
  var PagingQueueView;
  return PagingQueueView = (function(_super) {

    __extends(PagingQueueView, _super);

    function PagingQueueView() {
      return PagingQueueView.__super__.constructor.apply(this, arguments);
    }

    PagingQueueView.prototype.events = {
      'click': function(e) {
        var $target;
        $target = $(e.target);
        if ($target.attr('data-more-button') != null) {
          return this.model.load();
        }
      }
    };

    PagingQueueView.prototype.render = function() {
      PagingQueueView.__super__.render.apply(this, arguments);
      if (this.model.stack.length === this.model.count) {
        return this.$el.find("[data-more-button]").hide();
      }
    };

    return PagingQueueView;

  })(QueueView);
});
