// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST', 'jqueryui', 'chaplin', 'views/base/editable'], function(View, JST, jqueryui, Chaplin, EditableView) {
  'use strict';
  var QueueView,
    _this = this;
  return QueueView = (function(_super) {

    __extends(QueueView, _super);

    function QueueView() {
      var _this = this;
      this.del = function(id) {
        return QueueView.prototype.del.apply(_this, arguments);
      };
      this.add = function(model) {
        return QueueView.prototype.add.apply(_this, arguments);
      };
      return QueueView.__super__.constructor.apply(this, arguments);
    }

    QueueView.prototype.autoRender = false;

    QueueView.prototype.initialize = function() {
      QueueView.__super__.initialize.apply(this, arguments);
      Chaplin.mediator.subscribe('modelAdded', this.add);
      return Chaplin.mediator.subscribe('modelDeleted', this.del);
    };

    QueueView.prototype.regions = {
      '#elements': 'elements'
    };

    QueueView.prototype.add = function(model) {
      if (model.name === this.model.elementName) {
        this.model.pushElement(model);
        return this.render();
      }
    };

    QueueView.prototype.del = function(id) {
      return this.model.removeDeleted();
    };

    QueueView.prototype.render = function() {
      var el, element, _i, _len, _ref,
        _this = this;
      QueueView.__super__.render.apply(this, arguments);
      _ref = this.model.elements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        el = this.createElementView(element).setRegion('elements');
        if (el instanceof EditableView) {
          el.setMode('passive');
        } else {
          el.render();
        }
      }
      if (this.sortable) {
        return this.$el.find('.sortable').sortable({
          cursor: 'move',
          update: function() {
            return _this.updateOrder();
          }
        });
      }
    };

    QueueView.prototype.updateOrder = function() {
      var element, id, model, place, _i, _len, _ref,
        _this = this;
      place = 0;
      _ref = this.$el.find('.element');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        id = $(element).attr('id');
        model = this.model.getElementById(id);
        model.data.place = ++place;
      }
      return this.model.updatePlaces(function() {
        return _this.render();
      });
    };

    QueueView.prototype.getTemplateData = function() {
      return {};
    };

    QueueView.prototype.createElementView = function() {
      throw "Abstract method 'createElementView' must be redefined";
    };

    return QueueView;

  })(View);
});
