// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'routes', 'controllers/redirect-controller'], function(Chaplin, routes, RedirectController) {
  'use strict';
  var Application;
  return Application = (function(_super) {

    __extends(Application, _super);

    function Application() {
      return Application.__super__.constructor.apply(this, arguments);
    }

    Application.prototype.title = 'Yasoon site';

    Application.prototype.initialize = function() {
      Application.__super__.initialize.apply(this, arguments);
      this.initRouter(routes, {
        pushState: false
      });
      this.initDispatcher({
        controllerSuffix: '-controller'
      });
      this.initControllers();
      this.initLayout();
      this.initComposer();
      this.initMediator();
      this.startRouting();
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    Application.prototype.initMediator = function() {
      return Chaplin.mediator.seal();
    };

    Application.prototype.initControllers = function() {
      return new RedirectController();
    };

    return Application;

  })(Chaplin.Application);
});
