// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'routes', 'controllers/redirect-controller', 'controllers/message-controller', 'controllers/login-controller'], function(Chaplin, routes, RedirectController, MessageController, LoginController) {
  'use strict';
  var Application, _ref;
  return Application = (function(_super) {
    __extends(Application, _super);

    function Application() {
      _ref = Application.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Application.prototype.title = 'Yasoon site';

    Application.prototype.initialize = function() {
      Application.__super__.initialize.apply(this, arguments);
      return this.initControllers();
    };

    Application.prototype.initControllers = function() {
      new RedirectController();
      new MessageController();
      return new LoginController();
    };

    return Application;

  })(Chaplin.Application);
});
