// Generated by CoffeeScript 1.6.1

define(function() {
  'use strict';  return function(match) {
    match('register', 'register#indexAction');
    match('people', 'people#peopleAction');
    match('people/:catId', 'people#peopleAction');
    match('explore/:mode', 'people#exploreAction');
    match('explore/:mode/:catId', 'people#exploreAction');
    match('author/:authorId/posts/new', 'author#newPostAction');
    match('author/:authorId/posts/:postId', 'author#readPostAction');
    match('author/:authorId/posts', 'author#postsAction');
    match('author/:authorId/questions', 'author#questionsAction');
    match('admin/blank', 'admin#blankAction');
    match('admin/stories', 'admin#storiesAction');
    match('stories', 'index#storiesAction');
    return match('', 'index#indexAction');
  };
});
