// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var AuthorQuestionsQuestionModel, _ref;
  return AuthorQuestionsQuestionModel = (function(_super) {
    __extends(AuthorQuestionsQuestionModel, _super);

    function AuthorQuestionsQuestionModel() {
      _ref = AuthorQuestionsQuestionModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AuthorQuestionsQuestionModel.prototype.name = 'AuthorQuestionsQuestion';

    AuthorQuestionsQuestionModel.prototype.initialize = function(params) {
      AuthorQuestionsQuestionModel.__super__.initialize.call(this, params);
      return this.authorId = params.authorId;
    };

    AuthorQuestionsQuestionModel.prototype.update = function(callback) {
      var updateCallback,
        _this = this;
      if (!this.validateNotNull('caption', 'answer')) {
        this.publishEvent('publicError', 'Поля вопроса и ответа должны быть заполнены');
        return;
      }
      this.method = 'POST';
      this.url = function() {
        return 'api/question/update';
      };
      this.requestData = {
        model: {
          id: this.data.id,
          caption: this.data.caption,
          answer: this.data.answer
        }
      };
      updateCallback = function() {
        _this.publishEvent('modelUpdated', _this);
        return typeof callback === "function" ? callback() : void 0;
      };
      return this.request(updateCallback);
    };

    AuthorQuestionsQuestionModel.prototype.add = function(callback) {
      var addCallback,
        _this = this;
      if (!this.validateNotNull('caption')) {
        this.publishEvent('publicError', 'Тест вопроса не может быть пустым');
        return;
      }
      this.method = 'POST';
      this.url = function() {
        return 'api/question/add';
      };
      this.requestData = {
        model: {
          caption: this.data.caption,
          authorId: this.authorId
        }
      };
      addCallback = function() {
        var addedModel;
        addedModel = new AuthorQuestionsQuestionModel(_this.authorId);
        addedModel.data = {
          id: _this.data.id,
          place: _this.data.place,
          caption: _this.data.caption,
          date: _this.data.date
        };
        _this.data = {};
        _this.publishEvent('modelAdded', addedModel);
        return typeof callback === "function" ? callback() : void 0;
      };
      return this.request(addCallback);
    };

    AuthorQuestionsQuestionModel.prototype["delete"] = function(callback) {
      var deleteCallback,
        _this = this;
      this.method = 'POST';
      this.url = function() {
        return 'api/question/delete';
      };
      this.requestData = {
        model: {
          id: this.data.id
        }
      };
      deleteCallback = function() {
        _this.publishEvent('modelDeleted', _this.data.id);
        return typeof callback === "function" ? callback() : void 0;
      };
      return this.request(deleteCallback);
    };

    return AuthorQuestionsQuestionModel;

  })(Model);
});
