// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var AuthorPosts;
  return AuthorPosts = (function(_super) {

    __extends(AuthorPosts, _super);

    function AuthorPosts() {
      return AuthorPosts.__super__.constructor.apply(this, arguments);
    }

    AuthorPosts.prototype.fetch = function(callback) {
      this.url = function() {
        return "api/author/get_posts/" + this.id;
      };
      return this.request(callback);
    };

    AuthorPosts.prototype.initialize = function() {
      AuthorPosts.__super__.initialize.apply(this, arguments);
      return this.subscribeEvent('postAdded', this.postAddedHandler);
    };

    AuthorPosts.prototype.postAddedHandler = function(post) {
      if (this.id === post.authorId) {
        this.data.unshift(post);
        return this.trigger('updated');
      }
    };

    return AuthorPosts;

  })(Model);
});
