// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var Post;
  return Post = (function(_super) {

    __extends(Post, _super);

    function Post() {
      return Post.__super__.constructor.apply(this, arguments);
    }

    Post.prototype.fetch = function(callback) {
      this.url = function() {
        return "api/post/get/" + this.id;
      };
      this.fetchParams.method = "GET";
      this.fetchParams.data = {};
      return this.request(callback);
    };

    Post.prototype.update = function(callback) {
      var editCallback,
        _this = this;
      this.fetchParams.method = "POST";
      this.fetchParams.data = {
        model: {
          id: this.data.id,
          authorId: this.data.authorId,
          caption: this.data.caption,
          preview: this.data.preview,
          text: this.data.text
        }
      };
      this.url = function() {
        return "api/post/update";
      };
      editCallback = function() {
        _this.publishEvent('postUpdated', _this.data);
        return callback();
      };
      return this.request(editCallback);
    };

    Post.prototype.add = function(callback) {
      var addCallback,
        _this = this;
      this.fetchParams.method = "POST";
      this.fetchParams.data = {
        model: {
          authorId: this.data.authorId,
          caption: this.data.caption,
          preview: this.data.preview,
          text: this.data.text
        }
      };
      this.url = function() {
        return "api/post/add";
      };
      addCallback = function() {
        _this.publishEvent('postAdded', _this.data);
        return callback();
      };
      return this.request(addCallback);
    };

    Post.prototype["delete"] = function(callback) {
      var deleteCallback,
        _this = this;
      this.fetchParams.method = "POST";
      this.fetchParams.data = {
        model: {
          id: this.data.id
        }
      };
      this.url = function() {
        return "api/post/delete";
      };
      deleteCallback = function() {
        _this.publishEvent('postDeleted', _this.data);
        return callback();
      };
      return this.request(deleteCallback());
    };

    Post.prototype.sync = function(callback) {
      if (this.data.id) {
        return this.update(callback);
      } else {
        return this.add(callback);
      }
    };

    return Post;

  })(Model);
});
