// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var PostQuestionsQueue;
  return PostQuestionsQueue = (function(_super) {

    __extends(PostQuestionsQueue, _super);

    function PostQuestionsQueue() {
      return PostQuestionsQueue.__super__.constructor.apply(this, arguments);
    }

    PostQuestionsQueue.prototype.fetch = function(callback) {
      this.url = function() {
        return "api/post/get_questions/" + this.id;
      };
      this.fetchParams = {
        method: 'GET',
        data: {}
      };
      return this.request(callback);
    };

    PostQuestionsQueue.prototype.initialize = function() {
      PostQuestionsQueue.__super__.initialize.apply(this, arguments);
      return this.subscribeEvent('questionAdded', this.questionAddedHandler);
    };

    PostQuestionsQueue.prototype.questionAddedHandler = function(post) {
      if (this.id === post.authorId) {
        this.data.unshift(post);
        return this.trigger('updated');
      }
    };

    return PostQuestionsQueue;

  })(Model);
});
