// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var HeaderAdminBlank;
  return HeaderAdminBlank = (function(_super) {

    __extends(HeaderAdminBlank, _super);

    function HeaderAdminBlank() {
      return HeaderAdminBlank.__super__.constructor.apply(this, arguments);
    }

    HeaderAdminBlank.prototype.autoRender = true;

    HeaderAdminBlank.prototype.className = 'inside';

    HeaderAdminBlank.prototype.region = 'header';

    HeaderAdminBlank.prototype.templateName = 'header_admin_blank';

    return HeaderAdminBlank;

  })(View);
});
