// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var HeaderAuthorPosts;
  return HeaderAuthorPosts = (function(_super) {

    __extends(HeaderAuthorPosts, _super);

    function HeaderAuthorPosts() {
      return HeaderAuthorPosts.__super__.constructor.apply(this, arguments);
    }

    HeaderAuthorPosts.prototype.autoRender = true;

    HeaderAuthorPosts.prototype.className = 'inside';

    HeaderAuthorPosts.prototype.region = 'header';

    HeaderAuthorPosts.prototype.templateName = 'header_author_posts';

    HeaderAuthorPosts.prototype.events = {
      'click #loginButton': function() {
        return this.publishEvent('login');
      },
      'click #logoutButton': function() {
        return this.publishEvent('logout');
      }
    };

    HeaderAuthorPosts.prototype.initialize = function() {
      return HeaderAuthorPosts.__super__.initialize.apply(this, arguments);
    };

    HeaderAuthorPosts.prototype.getTemplateData = function() {
      return {
        authorized: this.authorized
      };
    };

    return HeaderAuthorPosts;

  })(View);
});
