// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var HeaderAuthorNewPost;
  return HeaderAuthorNewPost = (function(_super) {

    __extends(HeaderAuthorNewPost, _super);

    function HeaderAuthorNewPost() {
      return HeaderAuthorNewPost.__super__.constructor.apply(this, arguments);
    }

    HeaderAuthorNewPost.prototype.autoRender = true;

    HeaderAuthorNewPost.prototype.className = 'inside';

    HeaderAuthorNewPost.prototype.region = 'header';

    HeaderAuthorNewPost.prototype.templateName = 'header_author_newPost';

    HeaderAuthorNewPost.prototype.events = {
      'click #loginButton': function() {
        return this.publishEvent('login');
      },
      'click #logoutButton': function() {
        return this.publishEvent('logout');
      }
    };

    HeaderAuthorNewPost.prototype.initialize = function() {
      return HeaderAuthorNewPost.__super__.initialize.apply(this, arguments);
    };

    HeaderAuthorNewPost.prototype.getTemplateData = function() {
      return {
        authorized: this.authorized
      };
    };

    return HeaderAuthorNewPost;

  })(View);
});
