// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var IndexDaystoryModel, _ref;
  return IndexDaystoryModel = (function(_super) {
    __extends(IndexDaystoryModel, _super);

    function IndexDaystoryModel() {
      _ref = IndexDaystoryModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    IndexDaystoryModel.prototype.name = 'IndexDaystory';

    IndexDaystoryModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/post/get_daystory';
      };
      this.method = 'GET';
      return this.request(callback);
    };

    return IndexDaystoryModel;

  })(Model);
});
