// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var AuthorPostsHeaderView;
  return AuthorPostsHeaderView = (function(_super) {

    __extends(AuthorPostsHeaderView, _super);

    function AuthorPostsHeaderView() {
      return AuthorPostsHeaderView.__super__.constructor.apply(this, arguments);
    }

    AuthorPostsHeaderView.prototype.autoRender = true;

    AuthorPostsHeaderView.prototype.className = 'inside';

    AuthorPostsHeaderView.prototype.region = 'header';

    AuthorPostsHeaderView.prototype.templateName = 'author_posts_header';

    return AuthorPostsHeaderView;

  })(View);
});
