// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST', 'categories'], function(View, JST, categories) {
  'use strict';
  var AuthorPostsInfoView, _ref;
  return AuthorPostsInfoView = (function(_super) {
    __extends(AuthorPostsInfoView, _super);

    function AuthorPostsInfoView() {
      this.render = __bind(this.render, this);
      _ref = AuthorPostsInfoView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AuthorPostsInfoView.prototype.className = 'info';

    AuthorPostsInfoView.prototype.templateName = 'author_posts_info';

    AuthorPostsInfoView.prototype.events = {
      'click #follow': function() {
        this.model.follow();
        return this.drawUnfollow();
      },
      'click #unfollow': function() {
        this.model.unfollow();
        return this.drawFollow();
      }
    };

    AuthorPostsInfoView.prototype.render = function() {
      AuthorPostsInfoView.__super__.render.apply(this, arguments);
      if (this.model.access !== 'ANON') {
        if (this.model.data.is_friend) {
          return this.drawUnfollow();
        } else {
          return this.drawFollow();
        }
      }
    };

    AuthorPostsInfoView.prototype.drawFollow = function() {
      if (this.model.access !== 'US') {
        this.$el.find('#follow').show();
      }
      return this.$el.find('#unfollow').hide();
    };

    AuthorPostsInfoView.prototype.drawUnfollow = function() {
      this.$el.find('#follow').hide();
      if (this.model.access !== 'US') {
        return this.$el.find('#unfollow').show();
      }
    };

    return AuthorPostsInfoView;

  })(View);
});
