// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AuthorPostsPostView;
  return AuthorPostsPostView = (function(_super) {

    __extends(AuthorPostsPostView, _super);

    function AuthorPostsPostView() {
      return AuthorPostsPostView.__super__.constructor.apply(this, arguments);
    }

    AuthorPostsPostView.prototype.className = 'post';

    AuthorPostsPostView.prototype.templateName = 'author_posts_post';

    AuthorPostsPostView.prototype.modes = ['active', 'preview', 'passive', 'full'];

    AuthorPostsPostView.prototype.addCallback = function() {
      return this.publishEvent('redirect', "author/" + this.model.authorId + "/posts");
    };

    return AuthorPostsPostView;

  })(EditableView);
});
