// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var AuthorInfo,
    _this = this;
  return AuthorInfo = (function(_super) {

    __extends(AuthorInfo, _super);

    function AuthorInfo() {
      var _this = this;
      this.fetch = function(callback) {
        return AuthorInfo.prototype.fetch.apply(_this, arguments);
      };
      return AuthorInfo.__super__.constructor.apply(this, arguments);
    }

    AuthorInfo.prototype.fetch = function(callback) {
      var fetchCallback,
        _this = this;
      this.fetchParams = {};
      this.fetchParams.method = "GET";
      this.fetchParams.data = {};
      this.url = function() {
        return "api/author/get_short_info/" + this.id;
      };
      fetchCallback = function() {
        return typeof callback === "function" ? callback() : void 0;
      };
      return this.request(fetchCallback);
    };

    return AuthorInfo;

  })(Model);
});
