// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/admin/content/row'], function(Queue, RowModel) {
  'use strict';
  var AdminContentRowQueueModel, _ref;
  return AdminContentRowQueueModel = (function(_super) {
    __extends(AdminContentRowQueueModel, _super);

    function AdminContentRowQueueModel() {
      _ref = AdminContentRowQueueModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminContentRowQueueModel.prototype.name = 'AdminContentRowQueue';

    AdminContentRowQueueModel.prototype.elementName = 'AdminContentRow';

    AdminContentRowQueueModel.prototype.sortable = false;

    AdminContentRowQueueModel.prototype.load = function(callback) {
      var elData, key;
      this.elements = [];
      console.log(this.elements);
      for (key in managedContent) {
        elData = managedContent[key];
        this.elements.push(this.createElementModel(elData));
      }
      return typeof callback === "function" ? callback() : void 0;
    };

    AdminContentRowQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new RowModel();
      model.data = elData;
      return model;
    };

    return AdminContentRowQueueModel;

  })(Queue);
});
