// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin'], function(Chaplin) {
  var Model;
  return Model = (function(_super) {

    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.prototype.data = {};

    Model.prototype.fetchParams = {
      method: 'GET',
      data: {}
    };

    Model.prototype.formatUrl = function(url) {
      return "http://localhost:83/" + url;
    };

    Model.prototype.fetch = function(callback) {
      var request,
        _this = this;
      request = {
        url: this.formatUrl(this.url()),
        method: this.fetchParams.method,
        requestData: this.fetchParams.data
      };
      return $.ajax({
        url: request.url,
        method: request.method,
        data: request.requestData,
        success: function(data) {
          _this.data = data;
          return typeof callback === "function" ? callback() : void 0;
        }
      });
    };

    return Model;

  })(Chaplin.Model);
});
