// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin'], function(Chaplin) {
  var Model;
  return Model = (function(_super) {

    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.prototype.data = {};

    Model.prototype.url = '';

    Model.prototype.method = '';

    Model.prototype.requestData = '';

    Model.prototype.formatUrl = function(url) {
      return 'http://' + document.domain + ("/" + url);
    };

    Model.prototype.request = function(callback) {
      var _this = this;
      return $.ajax({
        url: this.formatUrl(this.url()),
        method: this.method,
        data: this.requestData,
        success: function(data) {
          _this.data = data;
          return typeof callback === "function" ? callback(data) : void 0;
        }
      });
    };

    return Model;

  })(Chaplin.Model);
});
