// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

define(['chaplin'], function(Chaplin) {
  var Model;
  return Model = (function(_super) {

    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.prototype.data = {};

    Model.prototype.url = '';

    Model.prototype.method = '';

    Model.prototype.requestData = '';

    Model.prototype.initialize = function() {
      Model.__super__.initialize.apply(this, arguments);
      if (this.name == null) {
        throw 'Model name must be defined';
      }
    };

    Model.prototype.formatUrl = function(url) {
      return 'http://' + document.domain + ("/" + url);
    };

    Model.prototype.validateNotNull = function() {
      var field, fields, _i, _len;
      fields = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      for (_i = 0, _len = fields.length; _i < _len; _i++) {
        field = fields[_i];
        if ((this.data[field] == null) || this.data[field] === '') {
          return false;
        }
      }
      return true;
    };

    Model.prototype.request = function(callback, dontUpdateData) {
      var _this = this;
      if (dontUpdateData == null) {
        dontUpdateData = false;
      }
      return $.ajax({
        url: this.formatUrl(this.url()),
        method: this.method,
        data: this.requestData,
        success: function(data) {
          if (!dontUpdateData) {
            _this.data = data;
          }
          return typeof callback === "function" ? callback(data) : void 0;
        }
      });
    };

    return Model;

  })(Chaplin.Model);
});
