// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page-view', 'JST'], function(PageView, JST) {
  'use strict';
  var AdminBlankPageView;
  return AdminBlankPageView = (function(_super) {

    __extends(AdminBlankPageView, _super);

    function AdminBlankPageView() {
      return AdminBlankPageView.__super__.constructor.apply(this, arguments);
    }

    AdminBlankPageView.prototype.className = 'postPage';

    AdminBlankPageView.prototype.regions = {
      '#queue': 'queue',
      '#new': 'new'
    };

    AdminBlankPageView.prototype.templateName = 'admin_blank-page';

    return AdminBlankPageView;

  })(PageView);
});
