// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var AuthorQuestionsHeaderView;
  return AuthorQuestionsHeaderView = (function(_super) {

    __extends(AuthorQuestionsHeaderView, _super);

    function AuthorQuestionsHeaderView() {
      return AuthorQuestionsHeaderView.__super__.constructor.apply(this, arguments);
    }

    AuthorQuestionsHeaderView.prototype.autoRender = true;

    AuthorQuestionsHeaderView.prototype.className = 'inside';

    AuthorQuestionsHeaderView.prototype.region = 'header';

    AuthorQuestionsHeaderView.prototype.templateName = 'author_questions_header';

    return AuthorQuestionsHeaderView;

  })(View);
});
