// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AuthorQuestionsQuesionView;
  return AuthorQuestionsQuesionView = (function(_super) {

    __extends(AuthorQuestionsQuesionView, _super);

    function AuthorQuestionsQuesionView() {
      return AuthorQuestionsQuesionView.__super__.constructor.apply(this, arguments);
    }

    AuthorQuestionsQuesionView.prototype.className = 'question';

    AuthorQuestionsQuesionView.prototype.tagName = 'article';

    AuthorQuestionsQuesionView.prototype.templateName = 'author_questions_question';

    AuthorQuestionsQuesionView.prototype.modes = ['passive', 'active', 'button', 'new_active', 'sent'];

    AuthorQuestionsQuesionView.prototype.addCallback = function() {
      return this.setMode('sent');
    };

    return AuthorQuestionsQuesionView;

  })(EditableView);
});
