// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/posts/header', 'models/timeline/postQueue', 'views/timeline/postQueue', 'models/index/header'], function(PageView, JST, FooterView, HeaderView, TimelinePostQueueModel, TimelinePostQueueView, HeaderModel) {
  'use strict';
  var TimelinePageView, _ref;
  return TimelinePageView = (function(_super) {
    __extends(TimelinePageView, _super);

    function TimelinePageView() {
      _ref = TimelinePageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TimelinePageView.prototype.className = 'timelinePage';

    TimelinePageView.prototype.regions = {
      'queue': '#queue',
      'footer': 'footer',
      'header': 'header'
    };

    TimelinePageView.prototype.templateName = 'timeline_page';

    TimelinePageView.prototype.initialize = function() {
      return TimelinePageView.__super__.initialize.apply(this, arguments);
    };

    TimelinePageView.prototype.render = function() {
      var hModel, tq,
        _this = this;
      TimelinePageView.__super__.render.apply(this, arguments);
      hModel = new HeaderModel();
      hModel.load(function() {
        return (new HeaderView({
          model: hModel,
          catId: _this.activeCategoryId,
          mode: _this.mode
        })).render();
      });
      new FooterView();
      tq = new TimelinePostQueueModel();
      return tq.load(function() {
        var tqView;
        tqView = new TimelinePostQueueView({
          model: tq
        });
        return tqView.setRegion('queue').render();
      });
    };

    return TimelinePageView;

  })(PageView);
});
