// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/pagingQueue', 'JST', 'views/timeline/post', 'views/timeline/question', 'views/timeline/blank'], function(PagingQueueView, JST, PostView, QuestionView, BlankView) {
  'use strict';
  var TimelinePostQueueView, _ref;
  return TimelinePostQueueView = (function(_super) {
    __extends(TimelinePostQueueView, _super);

    function TimelinePostQueueView() {
      _ref = TimelinePostQueueView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TimelinePostQueueView.prototype.className = 'TimelinePostQueue';

    TimelinePostQueueView.prototype.templateName = 'timeline_post_queue';

    TimelinePostQueueView.prototype.placeholder = 'timeline_placeholder';

    TimelinePostQueueView.prototype.sortable = true;

    TimelinePostQueueView.prototype.createElementView = function(model) {
      if (model.data.type === 'p') {
        return new PostView({
          model: model
        });
      } else if (model.data.type === 'q') {
        return new QuestionView({
          model: model
        });
      } else if (model.data.type === 'b') {
        return new BlankView({
          model: model
        });
      }
    };

    return TimelinePostQueueView;

  })(PagingQueueView);
});
