// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var TimelinePostAuthorView;
  return TimelinePostAuthorView = (function(_super) {

    __extends(TimelinePostAuthorView, _super);

    function TimelinePostAuthorView() {
      return TimelinePostAuthorView.__super__.constructor.apply(this, arguments);
    }

    TimelinePostAuthorView.prototype.className = 'author';

    TimelinePostAuthorView.prototype.templateName = 'timeline_post';

    return TimelinePostAuthorView;

  })(View);
});
