// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var TimelinePostView, _ref;
  return TimelinePostView = (function(_super) {
    __extends(TimelinePostView, _super);

    function TimelinePostView() {
      _ref = TimelinePostView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TimelinePostView.prototype.className = 'element';

    TimelinePostView.prototype.templateName = 'timeline_post';

    return TimelinePostView;

  })(View);
});
