// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var TimelineQuestionView, _ref;
  return TimelineQuestionView = (function(_super) {
    __extends(TimelineQuestionView, _super);

    function TimelineQuestionView() {
      _ref = TimelineQuestionView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TimelineQuestionView.prototype.className = 'element';

    TimelineQuestionView.prototype.templateName = 'timeline_question';

    return TimelineQuestionView;

  })(View);
});
