// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var PeopleExplorePostView, _ref;
  return PeopleExplorePostView = (function(_super) {
    __extends(PeopleExplorePostView, _super);

    function PeopleExplorePostView() {
      _ref = PeopleExplorePostView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PeopleExplorePostView.prototype.className = 'author';

    PeopleExplorePostView.prototype.templateName = 'people_explore_post';

    return PeopleExplorePostView;

  })(View);
});
