// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/people/explore/post'], function(QueueView, JST, PostView) {
  'use strict';
  var PeopleExplorePostQueueView, _ref;
  return PeopleExplorePostQueueView = (function(_super) {
    __extends(PeopleExplorePostQueueView, _super);

    function PeopleExplorePostQueueView() {
      _ref = PeopleExplorePostQueueView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PeopleExplorePostQueueView.prototype.className = 'PeopleExplorePostQueue';

    PeopleExplorePostQueueView.prototype.templateName = 'people_explore_post_queue';

    PeopleExplorePostQueueView.prototype.placeholder = 'people_author_queue_placeholder';

    PeopleExplorePostQueueView.prototype.sortable = true;

    PeopleExplorePostQueueView.prototype.createElementView = function(model) {
      return new PostView({
        model: model
      });
    };

    return PeopleExplorePostQueueView;

  })(QueueView);
});
