// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var AuthorInfoView;
  return AuthorInfoView = (function(_super) {

    __extends(AuthorInfoView, _super);

    function AuthorInfoView() {
      return AuthorInfoView.__super__.constructor.apply(this, arguments);
    }

    AuthorInfoView.prototype.autoRender = true;

    AuthorInfoView.prototype.className = 'authorInfo';

    AuthorInfoView.prototype.region = 'info';

    AuthorInfoView.prototype.templateName = 'author_info';

    AuthorInfoView.prototype.render = function() {
      AuthorInfoView.__super__.render.apply(this, arguments);
      return this.manageAuthAreas();
    };

    AuthorInfoView.prototype.getTemplateData = function() {
      return {
        author: this.model.data,
        authorized: this.authorized
      };
    };

    return AuthorInfoView;

  })(View);
});
