// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var AuthorPostPreviewView;
  return AuthorPostPreviewView = (function(_super) {

    __extends(AuthorPostPreviewView, _super);

    function AuthorPostPreviewView() {
      return AuthorPostPreviewView.__super__.constructor.apply(this, arguments);
    }

    AuthorPostPreviewView.prototype.autoRender = true;

    AuthorPostPreviewView.prototype.className = 'content';

    AuthorPostPreviewView.prototype.region = 'list';

    AuthorPostPreviewView.prototype.templateName = 'author_postPreview';

    AuthorPostPreviewView.prototype.getTemplateData = function() {
      return {
        author: this.model.data
      };
    };

    return AuthorPostPreviewView;

  })(View);
});
