// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/admin/header', 'views/admin/stories/postQueue', 'models/admin/stories/postQueue'], function(PageView, JST, FooterView, HeaderView, StoryQueueView, StoryQueueModel) {
  'use strict';
  var AdminStoriesPageView, _ref;
  return AdminStoriesPageView = (function(_super) {
    __extends(AdminStoriesPageView, _super);

    function AdminStoriesPageView() {
      _ref = AdminStoriesPageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminStoriesPageView.prototype.className = 'AdminStoriesPage';

    AdminStoriesPageView.prototype.regions = {
      '#queue': 'queue',
      'footer': 'footer',
      'header': 'header'
    };

    AdminStoriesPageView.prototype.templateName = 'admin_stories_page';

    AdminStoriesPageView.prototype.render = function() {
      var qsModel,
        _this = this;
      AdminStoriesPageView.__super__.render.apply(this, arguments);
      new HeaderView();
      new FooterView();
      qsModel = new StoryQueueModel();
      return qsModel.load(function() {
        return (new StoryQueueView({
          model: qsModel
        })).setRegion('queue').render();
      });
    };

    return AdminStoriesPageView;

  })(PageView);
});
