// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/admin/stories/post'], function(QueueView, JST, PostView) {
  'use strict';
  var AdminStoriesPostQueueView;
  return AdminStoriesPostQueueView = (function(_super) {

    __extends(AdminStoriesPostQueueView, _super);

    function AdminStoriesPostQueueView() {
      return AdminStoriesPostQueueView.__super__.constructor.apply(this, arguments);
    }

    AdminStoriesPostQueueView.prototype.className = 'storiesPostQueue';

    AdminStoriesPostQueueView.prototype.templateName = 'admin_stories_post_queue';

    AdminStoriesPostQueueView.prototype.sortable = false;

    AdminStoriesPostQueueView.prototype.createElementView = function(model) {
      return new PostView({
        model: model
      });
    };

    return AdminStoriesPostQueueView;

  })(QueueView);
});
