// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable'], function(EditableView) {
  'use strict';
  var InfoInfoView, _ref;
  return InfoInfoView = (function(_super) {
    __extends(InfoInfoView, _super);

    function InfoInfoView() {
      _ref = InfoInfoView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    InfoInfoView.prototype.className = 'info';

    InfoInfoView.prototype.templateName = 'info';

    InfoInfoView.prototype.modes = ['edit'];

    return InfoInfoView;

  })(EditableView);
});
