// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/posts/header', 'models/register/register', 'views/info/info'], function(PageView, JST, FooterView, HeaderView, InfoModel, InfoView) {
  'use strict';
  var InfoPageView, _ref;
  return InfoPageView = (function(_super) {
    __extends(InfoPageView, _super);

    function InfoPageView() {
      _ref = InfoPageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    InfoPageView.prototype.className = 'infoPage';

    InfoPageView.prototype.regions = {
      'footer': 'footer',
      'header': 'header',
      'info': '#page-layout'
    };

    InfoPageView.prototype.templateName = 'info_page';

    InfoPageView.prototype.render = function() {
      var infoModel,
        _this = this;
      InfoPageView.__super__.render.apply(this, arguments);
      new HeaderView();
      new FooterView();
      infoModel = new InfoModel();
      return infoModel.load(function() {
        var infoView;
        infoView = new InfoView({
          model: infoModel
        });
        infoView.setRegion('info').setMode('edit');
        console.log(infoModel);
        return $('#fileupload').fileupload({
          dataType: 'json',
          autoUpload: true,
          number: 1,
          done: function(e, data) {
            return $.each(data.result, function(index, file) {
              var fileName;
              fileName = file.dir + file.file_name;
              return $(".files_success_upload").append('<img src="' + fileName + '" width="53" height="53"/>');
            });
          }
        });
      });
    };

    return InfoPageView;

  })(PageView);
});
