// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var RegisterRegisterModel, _ref;
  return RegisterRegisterModel = (function(_super) {
    __extends(RegisterRegisterModel, _super);

    function RegisterRegisterModel() {
      _ref = RegisterRegisterModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RegisterRegisterModel.prototype.name = 'RegisterRegister';

    RegisterRegisterModel.prototype.add = function(callback) {
      var updateCallback,
        _this = this;
      if (!this.validateRegFields('name') || !this.validateRegFields('lastName') || !this.validateRegFields('password') || !this.validateEmail(this.data['email'])) {
        return;
      }
      this.method = 'POST';
      this.url = function() {
        return 'api/register';
      };
      this.requestData = {
        model: {
          name: this.data.name,
          lastName: this.data.lastName,
          email: this.data.email,
          password: this.data.password,
          shortHistory: this.data.shortHistory,
          job: this.data.job,
          interests: this.data.interests,
          dreams: this.data.dreams
        }
      };
      updateCallback = function() {
        _this.publishEvent('modelUpdated', _this);
        return typeof callback === "function" ? callback() : void 0;
      };
      console.log(this.data);
      return;
      return this.request(updateCallback);
    };

    RegisterRegisterModel.prototype.validateRegFields = function(fieldName) {
      var registerForm, statusValidate;
      registerForm = $(".register-form");
      statusValidate = false;
      if (!this.validateNotNull(fieldName)) {
        registerForm.find(".data_" + fieldName).show();
        statusValidate = false;
      } else {
        registerForm.find(".data_" + fieldName).hide();
        statusValidate = true;
      }
      return statusValidate;
    };

    return RegisterRegisterModel;

  })(Model);
});
