// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page-view', 'JST', 'views/footer', 'views/header/author_posts'], function(PageView, JST, FooterView, HeaderView) {
  'use strict';
  var AuthorQuestionsPageView;
  return AuthorQuestionsPageView = (function(_super) {

    __extends(AuthorQuestionsPageView, _super);

    function AuthorQuestionsPageView() {
      return AuthorQuestionsPageView.__super__.constructor.apply(this, arguments);
    }

    AuthorQuestionsPageView.prototype.className = 'postPage';

    AuthorQuestionsPageView.prototype.initialize = function(params) {
      AuthorQuestionsPageView.__super__.initialize.apply(this, arguments);
      return this.authorId = params.authorId;
    };

    AuthorQuestionsPageView.prototype.regions = {
      '#queue': 'queue',
      '#new': 'new',
      'footer': 'footer',
      'header': 'header',
      '#authorInfo': 'info'
    };

    AuthorQuestionsPageView.prototype.templateName = 'author_questions-page';

    AuthorQuestionsPageView.prototype.events = {
      'click #toStories': function() {
        return this.publishEvent('redirect', "#author/" + this.authorId + "/posts");
      },
      'click #toAnswers': function() {
        return this.publishEvent('redirect', "#author/" + this.authorId + "/questions");
      }
    };

    AuthorQuestionsPageView.prototype.render = function() {
      var footerView, headerView;
      AuthorQuestionsPageView.__super__.render.apply(this, arguments);
      footerView = new FooterView();
      return headerView = new HeaderView();
    };

    return AuthorQuestionsPageView;

  })(PageView);
});
