<?php

namespace Proxies\__CG__\Yasoon\Site\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FriendsEntity extends \Yasoon\Site\Entity\FriendsEntity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setReader($reader)
    {
        $this->__load();
        return parent::setReader($reader);
    }

    public function getReader()
    {
        $this->__load();
        return parent::getReader();
    }

    public function setWriter($writer)
    {
        $this->__load();
        return parent::setWriter($writer);
    }

    public function getWriter()
    {
        $this->__load();
        return parent::getWriter();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getDateWrite()
    {
        $this->__load();
        return parent::getDateWrite();
    }

    public function setDateWrite($date_write)
    {
        $this->__load();
        return parent::setDateWrite($date_write);
    }

    public function setWriterId($writerId)
    {
        $this->__load();
        return parent::setWriterId($writerId);
    }

    public function getWriterId()
    {
        $this->__load();
        return parent::getWriterId();
    }

    public function setReaderId($readerId)
    {
        $this->__load();
        return parent::setReaderId($readerId);
    }

    public function getReaderId()
    {
        $this->__load();
        return parent::getReaderId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'writerId', 'readerId', 'date_write', 'reader', 'writer');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}