// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/questions/header'], function(PageView, JST, FooterView, HeaderView) {
  'use strict';
  var BlogAgreementPageView, _ref;
  return BlogAgreementPageView = (function(_super) {
    __extends(BlogAgreementPageView, _super);

    function BlogAgreementPageView() {
      _ref = BlogAgreementPageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BlogAgreementPageView.prototype.className = 'agreementPage';

    BlogAgreementPageView.prototype.regions = {
      'footer': 'footer',
      'header': 'header'
    };

    BlogAgreementPageView.prototype.templateName = 'blog_agreement_page';

    BlogAgreementPageView.prototype.render = function() {
      var fv, hv;
      BlogAgreementPageView.__super__.render.apply(this, arguments);
      hv = new HeaderView();
      return fv = new FooterView();
    };

    return BlogAgreementPageView;

  })(PageView);
});
