// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var IndexStoriesPostModel;
  return IndexStoriesPostModel = (function(_super) {

    __extends(IndexStoriesPostModel, _super);

    function IndexStoriesPostModel() {
      return IndexStoriesPostModel.__super__.constructor.apply(this, arguments);
    }

    IndexStoriesPostModel.prototype.name = 'IndexStoriesPost';

    return IndexStoriesPostModel;

  })(Model);
});
