// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var BlogPageModel, _ref;
  return BlogPageModel = (function(_super) {
    __extends(BlogPageModel, _super);

    function BlogPageModel() {
      _ref = BlogPageModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BlogPageModel.prototype.name = 'BlogPageModel';

    BlogPageModel.prototype.follow = function(callback) {
      this.method = 'GET';
      this.url = function() {
        return 'api/friends/add/0/';
      };
      this.requestData = {};
      return this.request(callback);
    };

    BlogPageModel.prototype.unfollow = function(callback) {
      this.method = 'GET';
      this.url = function() {
        return 'api/friends/delete/0';
      };
      this.requestData = {};
      return this.request(callback);
    };

    return BlogPageModel;

  })(Model);
});
