// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST', 'models/blankQuestion/model', 'views/blankQuestion/view'], function(View, JST, BlankQuestion, BlankQuestionView) {
  'use strict';
  var BlankQuestionsQueueView;
  return BlankQuestionsQueueView = (function(_super) {

    __extends(BlankQuestionsQueueView, _super);

    function BlankQuestionsQueueView() {
      return BlankQuestionsQueueView.__super__.constructor.apply(this, arguments);
    }

    BlankQuestionsQueueView.prototype.className = 'list';

    BlankQuestionsQueueView.prototype.autoRender = true;

    BlankQuestionsQueueView.prototype.region = 'queue';

    BlankQuestionsQueueView.prototype.regions = {
      '#list': 'list'
    };

    BlankQuestionsQueueView.prototype.templateName = 'blankQuestion_queue';

    BlankQuestionsQueueView.prototype.render = function() {
      var question, _i, _len, _ref, _results;
      BlankQuestionsQueueView.__super__.render.apply(this, arguments);
      _ref = this.model.questions;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        question = _ref[_i];
        _results.push((new BlankQuestionView({
          model: question
        })).setRegion('list').setPassiveMode());
      }
      return _results;
    };

    return BlankQuestionsQueueView;

  })(View);
});
