// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var BlankQuestionView,
    _this = this;
  return BlankQuestionView = (function(_super) {

    __extends(BlankQuestionView, _super);

    function BlankQuestionView() {
      var _this = this;
      this.getTemplateData = function() {
        return BlankQuestionView.prototype.getTemplateData.apply(_this, arguments);
      };
      return BlankQuestionView.__super__.constructor.apply(this, arguments);
    }

    BlankQuestionView.prototype.templateName = 'blankQuestion_view';

    BlankQuestionView.prototype.autoRender = false;

    BlankQuestionView.prototype.className = 'blankQuestion';

    BlankQuestionView.prototype.tagName = 'li';

    BlankQuestionView.prototype.setActiveMode = function() {
      BlankQuestionView.__super__.setActiveMode.apply(this, arguments);
      return this.$el.find('.body').focus();
    };

    BlankQuestionView.prototype.events = {
      'click #newButton': function() {
        return this.setActiveMode();
      },
      'click .question': function() {
        if (this.mode === 'passive') {
          return this.setActiveMode();
        }
      },
      'keydown .body': function(e) {
        if (e.keyCode === 27) {
          return this.setPreviousMode();
        }
      },
      'keyup .body': function(e) {
        return this.model.data.text = $(e.target).val();
      },
      'click #sendButton': function(e) {
        var _this = this;
        this.$el.find('#buttons').hide();
        if (this.model.data.id != null) {
          return this.model.update(function() {
            return _this.setPreviousMode();
          });
        } else {
          return this.model.add(function() {
            return _this.setButtonMode();
          });
        }
      },
      'click #deleteButton': function(e) {
        var _this = this;
        this.$el.find('#buttons').hide();
        return this.model["delete"](function() {
          return _this.dispose();
        });
      }
    };

    BlankQuestionView.prototype.getTemplateData = function() {
      return {
        question: this.model.data
      };
    };

    return BlankQuestionView;

  })(EditableView);
});
