INSERT INTO content (id, text, description, tagId) VALUES ('101', 'Поиск по категориям', 'Заголовок для поиска на главной странице', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('102', 'Поиск по категориям', 'Подсказка для поиска на главной странице', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('103', 'Поиск...', 'Подсказка для поиска в попапе', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('104', 'Рейтинг', 'Заголовок для статистики в категориях "Рейтинг"', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('105', 'Перспективы', 'Заголовок для статистики в категориях "Перспективы"', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('106', 'Вопрос 1', 'Заголовок для статистики в категориях "Вопрос 1"', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('107', 'Вопрос 2', 'Заголовок для статистики в категориях "Вопрос 2"', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('108', 'Всего записей', 'Заголовок для статистики в категориях "Всего записей"', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('109', 'background-color: rgb(255, 242, 153);', 'Цвет фона для статистики отзывов', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('110', 'Рассказать историю', 'Кнопка на главной странице для создания поста', 'NULL');
INSERT INTO content (id, text, description, tagId) VALUES ('111', 'Рейтинг категории', 'Описание для рейтинга категорий', 'NULL');
