<?php

namespace HWI\Bundle\OAuthBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConnectController__JMSInjector
{
    public static function inject($container) {
        $instance = new \HWI\Bundle\OAuthBundle\Controller\ConnectController();
        return $instance;
    }
}
