<?php

namespace Yasoon\Site\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlankQuestionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Yasoon\Site\Controller\BlankQuestionController();
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\BlankQuestionController', 'securityContext');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('security.context', 1));
        return $instance;
    }
}
