<?php

namespace Yasoon\Site\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Yasoon\Site\Controller\PostController();
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\PostController', 'service');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.post', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\PostController', 'partnerservice');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.partner', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\PostController', 'postcategoryservice');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.postcategory', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\PostController', 'authorservice');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.author', 1));
        return $instance;
    }
}
