<?php

namespace Yasoon\Site\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AuthController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Yasoon\Site\Controller\AuthController();
        return $instance;
    }
}
