<?php

namespace Yasoon\Site\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AuthorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Yasoon\Site\Controller\AuthorController();
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\AuthorController', 'service');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.author', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\AuthorController', 'imageService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.image', 1));
        return $instance;
    }
}
