<?php

namespace Yasoon\Site\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Yasoon\Site\Controller\ContentController();
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\ContentController', 'securityContext');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('security.context', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\ContentController', 'service');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.content', 1));
        return $instance;
    }
}
