<?php

namespace Yasoon\Site\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApiSearchController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Yasoon\Site\Controller\ApiSearchController();
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\ApiSearchController', 'postservice');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.post', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\ApiSearchController', 'service');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.author', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\ApiSearchController', 'questionservice');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.question', 1));
        $refProperty = new \ReflectionProperty('Yasoon\\Site\\Controller\\ApiSearchController', 'allf');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('yasoon.service.allf', 1));
        $instance->mailer = $container->get('yasoon.mail.sender', 1);
        return $instance;
    }
}
