// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/index/header', 'views/index/stories/postQueue', 'models/index/stories/postQueue'], function(PageView, JST, FooterView, HeaderView, PostQueueView, PostQueueModel) {
  'use strict';
  var IndexStoriesPageView, _ref;
  return IndexStoriesPageView = (function(_super) {
    __extends(IndexStoriesPageView, _super);

    function IndexStoriesPageView() {
      _ref = IndexStoriesPageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    IndexStoriesPageView.prototype.className = 'indexPage';

    IndexStoriesPageView.prototype.regions = {
      'queue': '#queue',
      'footer': 'footer',
      'header': 'header'
    };

    IndexStoriesPageView.prototype.templateName = 'index_stories_page';

    IndexStoriesPageView.prototype.render = function() {
      var pq,
        _this = this;
      IndexStoriesPageView.__super__.render.apply(this, arguments);
      new HeaderView();
      new FooterView();
      pq = new PostQueueModel();
      return pq.load(function() {
        return (new PostQueueView({
          model: pq
        })).setRegion('queue').render();
      });
    };

    return IndexStoriesPageView;

  })(PageView);
});
