// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/index/stories/post', 'models/index/stories/post'], function(QueueView, JST, PostView) {
  'use strict';
  var IndexStoriesPostQueueView, _ref;
  return IndexStoriesPostQueueView = (function(_super) {
    __extends(IndexStoriesPostQueueView, _super);

    function IndexStoriesPostQueueView() {
      _ref = IndexStoriesPostQueueView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    IndexStoriesPostQueueView.prototype.className = 'IndexStoriesPostQueue';

    IndexStoriesPostQueueView.prototype.templateName = 'index_stories_post_queue';

    IndexStoriesPostQueueView.prototype.sortable = false;

    IndexStoriesPostQueueView.prototype.createElementView = function(model) {
      return new PostView({
        model: model
      });
    };

    return IndexStoriesPostQueueView;

  })(QueueView);
});
