// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var IndexStoriesPostView, _ref;
  return IndexStoriesPostView = (function(_super) {
    __extends(IndexStoriesPostView, _super);

    function IndexStoriesPostView() {
      _ref = IndexStoriesPostView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    IndexStoriesPostView.prototype.className = 'post';

    IndexStoriesPostView.prototype.templateName = 'index_stories_post';

    return IndexStoriesPostView;

  })(View);
});
