// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/posts/header'], function(PageView, JST, FooterView, HeaderView) {
  'use strict';
  var PeoplePageView;
  return PeoplePageView = (function(_super) {

    __extends(PeoplePageView, _super);

    function PeoplePageView() {
      return PeoplePageView.__super__.constructor.apply(this, arguments);
    }

    PeoplePageView.prototype.className = 'registerPage';

    PeoplePageView.prototype.regions = {
      'footer': 'footer',
      'header': 'header'
    };

    PeoplePageView.prototype.templateName = 'register_page';

    return PeoplePageView;

  })(PageView);
});
