// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/posts/header', 'lib/validate'], function(PageView, JST, FooterView, HeaderView, Validate) {
  'use strict';
  var PeoplePageView, _ref;
  return PeoplePageView = (function(_super) {
    __extends(PeoplePageView, _super);

    function PeoplePageView() {
      _ref = PeoplePageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PeoplePageView.prototype.className = 'registerPage';

    PeoplePageView.prototype.regions = {
      'footer': 'footer',
      'header': 'header'
    };

    PeoplePageView.prototype.templateName = 'register_page';

    PeoplePageView.prototype.events = {
      'click .regbtn': function() {
        var validator;
        return validator = new FormValidator('register-form', [
          {
            name: 'req',
            display: 'required',
            rules: 'required'
          }
        ], function(errors, event) {
          return log(errors);
        });
      }
    };

    return PeoplePageView;

  })(PageView);
});
