// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable'], function(EditableView) {
  'use strict';
  var RegisterRegisterView, _ref;
  return RegisterRegisterView = (function(_super) {
    __extends(RegisterRegisterView, _super);

    function RegisterRegisterView() {
      _ref = RegisterRegisterView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RegisterRegisterView.prototype.className = 'register';

    RegisterRegisterView.prototype.templateName = 'register';

    RegisterRegisterView.prototype.modes = ['active'];

    return RegisterRegisterView;

  })(EditableView);
});
