// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var AdminBlankHeaderView;
  return AdminBlankHeaderView = (function(_super) {

    __extends(AdminBlankHeaderView, _super);

    function AdminBlankHeaderView() {
      return AdminBlankHeaderView.__super__.constructor.apply(this, arguments);
    }

    AdminBlankHeaderView.prototype.autoRender = true;

    AdminBlankHeaderView.prototype.className = 'inside';

    AdminBlankHeaderView.prototype.region = 'header';

    AdminBlankHeaderView.prototype.templateName = 'admin_blank_header';

    return AdminBlankHeaderView;

  })(View);
});
