// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/admin/blank/questionTemplate', 'models/admin/blank/questionTemplate'], function(QueueView, JST, QuestionTemplateView, QuestionTemplateModel) {
  'use strict';
  var AdminBlankQuestionTemplateQueueView;
  return AdminBlankQuestionTemplateQueueView = (function(_super) {

    __extends(AdminBlankQuestionTemplateQueueView, _super);

    function AdminBlankQuestionTemplateQueueView() {
      return AdminBlankQuestionTemplateQueueView.__super__.constructor.apply(this, arguments);
    }

    AdminBlankQuestionTemplateQueueView.prototype.className = 'questionTemplateQueue';

    AdminBlankQuestionTemplateQueueView.prototype.templateName = 'admin_blank_question_template_queue';

    AdminBlankQuestionTemplateQueueView.prototype.sortable = true;

    AdminBlankQuestionTemplateQueueView.prototype.createElementView = function(model) {
      return new QuestionTemplateView({
        model: model
      });
    };

    return AdminBlankQuestionTemplateQueueView;

  })(QueueView);
});
