// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AdminBlankQuestionTemplateView, _ref;
  return AdminBlankQuestionTemplateView = (function(_super) {
    __extends(AdminBlankQuestionTemplateView, _super);

    function AdminBlankQuestionTemplateView() {
      _ref = AdminBlankQuestionTemplateView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminBlankQuestionTemplateView.prototype.className = 'questionTemplate';

    AdminBlankQuestionTemplateView.prototype.templateName = 'admin_blank_question_template';

    AdminBlankQuestionTemplateView.prototype.modes = ['button', 'passive', 'active'];

    AdminBlankQuestionTemplateView.prototype.addCallback = function() {
      return this.setMode('button');
    };

    return AdminBlankQuestionTemplateView;

  })(EditableView);
});
