// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AdminBlankQuestionTemplateView;
  return AdminBlankQuestionTemplateView = (function(_super) {

    __extends(AdminBlankQuestionTemplateView, _super);

    function AdminBlankQuestionTemplateView() {
      return AdminBlankQuestionTemplateView.__super__.constructor.apply(this, arguments);
    }

    AdminBlankQuestionTemplateView.prototype.className = 'questionTemplate';

    AdminBlankQuestionTemplateView.prototype.templateName = 'admin_blank_question_template';

    AdminBlankQuestionTemplateView.prototype.modes = ['button', 'passive', 'active'];

    AdminBlankQuestionTemplateView.prototype.events = {
      'keyup #text': function(e) {
        return this.model.data.text = $(e.target).val();
      },
      'keyup #caption': function(e) {
        return this.model.caption = $(e.target).html();
      }
    };

    return AdminBlankQuestionTemplateView;

  })(EditableView);
});
