// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/people/author'], function(Queue, AuthorModel) {
  'use strict';
  var PeopleAuthorQueueModel;
  return PeopleAuthorQueueModel = (function(_super) {

    __extends(PeopleAuthorQueueModel, _super);

    function PeopleAuthorQueueModel() {
      return PeopleAuthorQueueModel.__super__.constructor.apply(this, arguments);
    }

    PeopleAuthorQueueModel.prototype.name = 'PeopleAuthorQueue';

    PeopleAuthorQueueModel.prototype.elementName = 'PeopleAuthor';

    PeopleAuthorQueueModel.prototype.initialize = function(params) {
      PeopleAuthorQueueModel.__super__.initialize.call(this, params);
      return this.categoryId = params.categoryId;
    };

    PeopleAuthorQueueModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/people/get_authors/' + this.categoryId;
      };
      this.method = 'GET';
      return PeopleAuthorQueueModel.__super__.load.call(this, callback);
    };

    PeopleAuthorQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new AuthorModel();
      model.data = elData;
      return model;
    };

    return PeopleAuthorQueueModel;

  })(Queue);
});
