// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var PeopleAuthorModel;
  return PeopleAuthorModel = (function(_super) {

    __extends(PeopleAuthorModel, _super);

    function PeopleAuthorModel() {
      return PeopleAuthorModel.__super__.constructor.apply(this, arguments);
    }

    PeopleAuthorModel.prototype.name = 'PeopleAuthor';

    return PeopleAuthorModel;

  })(Model);
});
