// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/people/author'], function(Queue, AuthorModel) {
  'use strict';
  var PeopleAuthorSearchModel, _ref;
  return PeopleAuthorSearchModel = (function(_super) {
    __extends(PeopleAuthorSearchModel, _super);

    function PeopleAuthorSearchModel() {
      _ref = PeopleAuthorSearchModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PeopleAuthorSearchModel.prototype.name = 'PeopleAuthorQueue';

    PeopleAuthorSearchModel.prototype.elementName = 'PeopleAuthor';

    PeopleAuthorSearchModel.prototype.initialize = function(params) {
      PeopleAuthorSearchModel.__super__.initialize.call(this, params);
      return this.searchText = params.text;
    };

    PeopleAuthorSearchModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/people/search_author/' + this.searchText;
      };
      this.method = 'GET';
      return PeopleAuthorSearchModel.__super__.load.call(this, callback);
    };

    PeopleAuthorSearchModel.prototype.createElementModel = function(elData) {
      var model;
      model = new AuthorModel();
      model.data = elData;
      return model;
    };

    return PeopleAuthorSearchModel;

  })(Queue);
});
