<?php

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Psr\Log\LoggerInterface;

/**
 * appDevUrlGenerator
 *
 * This class has been auto-generated
 * by the Symfony Routing Component.
 */
class appDevUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    static private $declaredRoutes = array(
        'yasoon_site_admin_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AdminController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/',    ),  ),  4 =>   array (  ),),
        'yasoon_site_admin_getusers' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AdminController::getUsers',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/getUsers',    ),  ),  4 =>   array (  ),),
        'yasoon_site_answer_add' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AnswerController::addAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/answer/add',    ),  ),  4 =>   array (  ),),
        'yasoon_site_answer_update' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AnswerController::updateAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/answer/update',    ),  ),  4 =>   array (  ),),
        'yasoon_site_answer_remove' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AnswerController::removeAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/answer/delete',    ),  ),  4 =>   array (  ),),
        'yasoon_site_apisearch_get' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ApiSearchController::get',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/search/get',    ),  ),  4 =>   array (  ),),
        'yasoon_site_apisearch_test' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ApiSearchController::test',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/search/test',    ),  ),  4 =>   array (  ),),
        'yasoon_site_apisearch_actiontest' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ApiSearchController::actiontest',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/search/actiontest',    ),  ),  4 =>   array (  ),),
        'login_check' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthController::loginCheckAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login_check',    ),  ),  4 =>   array (  ),),
        'login' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthController::loginAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login',    ),  ),  4 =>   array (  ),),
        'logout' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthController::logoutAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),  ),  4 =>   array (  ),),
        'loginfail' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthController::fail',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login/fail',    ),  ),  4 =>   array (  ),),
        'loginfacebook' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthController::login_facebook',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login/facebook',    ),  ),  4 =>   array (  ),),
        'loginfacebookfail' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthController::login_facebook_fail',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login/facebook/fail',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_setfriends' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::setFriends',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/setFriends',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_setquestion' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::setQuestion',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/setQuestion',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_savequestionanswer' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::saveQuestionAnswer',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/saveQuestionAnswer',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getshortinfo' => array (  0 =>   array (    0 => 'authorId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getShortInfoAction',  ),  2 =>   array (    'authorId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'authorId',    ),    1 =>     array (      0 => 'text',      1 => '/api/author/get_short_info',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getshortuserdata' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getShortuserDataAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/getShortuserData',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_cleartimeline' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::clearTimeline',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/clearTimeline',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getstatusinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getStatusInfoAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/get_status_info',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getposts' => array (  0 =>   array (    0 => 'authorId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getPostsAction',  ),  2 =>   array (    'authorId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'authorId',    ),    1 =>     array (      0 => 'text',      1 => '/api/author/get_posts',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getauthorinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getAuthorInfo',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/getAuthorInfo',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getquestions' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getQuestionsAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/get_questions',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getquestionsstack' => array (  0 =>   array (    0 => 'authorId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getQuestionsStackAction',  ),  2 =>   array (    'authorId' => '\\d+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'authorId',    ),    1 =>     array (      0 => 'text',      1 => '/api/author/get_questions_stack',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_updatequestionsplaces' => array (  0 =>   array (    0 => 'authorId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::updateQuestionsPlaces',  ),  2 =>   array (    'authorId' => '\\d+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'authorId',    ),    1 =>     array (      0 => 'text',      1 => '/api/author/update_questions_places',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_updatepostsplaces' => array (  0 =>   array (    0 => 'authorId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::updatePostsPlaces',  ),  2 =>   array (    'authorId' => '\\d+',    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'authorId',    ),    1 =>     array (      0 => 'text',      1 => '/api/author/update_posts_places',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_getblank' => array (  0 =>   array (    0 => 'authorId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::getBlankAction',  ),  2 =>   array (    'authorId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'authorId',    ),    1 =>     array (      0 => 'text',      1 => '/api/author/get_blank',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_register' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::register',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/register',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_send_mail' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::send_mail',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/send_mail',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_editinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::editInfo',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/editinfo',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_notify' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::notify',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/notify',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_change_pass' => array (  0 =>   array (    0 => 'email',    1 => 'hash',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::change_pass',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'hash',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'email',    ),    2 =>     array (      0 => 'text',      1 => '/api/author/change_pass',    ),  ),  4 =>   array (  ),),
        'yasoon_site_author_uploaduserimage' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\AuthorController::uploadUserImage',  ),  2 =>   array (    '_method' => 'FILES|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/author/upload_user_image',    ),  ),  4 =>   array (  ),),
        'yasoon_site_blankquestion_getblank' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\BlankQuestionController::getBlankAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/blank_question/get_blank',    ),  ),  4 =>   array (  ),),
        'yasoon_site_blankquestion_add' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\BlankQuestionController::addAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/blank_question/add',    ),  ),  4 =>   array (  ),),
        'yasoon_site_blankquestion_update' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\BlankQuestionController::updateAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/blank_question/update',    ),  ),  4 =>   array (  ),),
        'yasoon_site_blankquestion_remove' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\BlankQuestionController::removeAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/blank_question/delete',    ),  ),  4 =>   array (  ),),
        'yasoon_site_blankquestion_updateplaces' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\BlankQuestionController::updatePlaces',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/blank_question/update_places',    ),  ),  4 =>   array (  ),),
        'yasoon_site_categories_categorylist' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\CategoriesController::categoryListAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/category/get_CategoryList',    ),  ),  4 =>   array (  ),),
        'yasoon_site_content_getallcontent' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ContentController::getAllContent',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/content/get_all',    ),  ),  4 =>   array (  ),),
        'yasoon_site_content_editrow' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ContentController::editRow',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/content/edit',    ),  ),  4 =>   array (  ),),
        'yasoon_site_content_addrow' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ContentController::addRow',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/content/add',    ),  ),  4 =>   array (  ),),
        'yasoon_site_content_deleterow' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\ContentController::deleteRow',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/content/delete',    ),  ),  4 =>   array (  ),),
        'yasoon_site_friends_add' => array (  0 =>   array (    0 => 'writerId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\FriendsController::addAction',  ),  2 =>   array (    'writerId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'writerId',    ),    1 =>     array (      0 => 'text',      1 => '/api/friends/add',    ),  ),  4 =>   array (  ),),
        'yasoon_site_friends_delete' => array (  0 =>   array (    0 => 'writerId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\FriendsController::deleteAction',  ),  2 =>   array (    'writerId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'writerId',    ),    1 =>     array (      0 => 'text',      1 => '/api/friends/delete',    ),  ),  4 =>   array (  ),),
        'yasoon_site_friends_gettimelinestack' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\FriendsController::getTimelineStackAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/friends/timeline_stack',    ),  ),  4 =>   array (  ),),
        'yasoon_site_friends_getadmintimelinestack' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\FriendsController::getAdminTimelineStackAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/friends/admin_timeline_stack',    ),  ),  4 =>   array (  ),),
        'yasoon_site_friends_gettimeline' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\FriendsController::getTimelineAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/friends/timeline',    ),  ),  4 =>   array (  ),),
        'yasoon_site_index_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\IndexController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),),
        'yasoon_site_index_admin' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\IndexController::adminAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin',    ),  ),  4 =>   array (  ),),
        'yasoon_site_index_test' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\IndexController::testAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/test_user',    ),  ),  4 =>   array (  ),),
        'yasoon_site_interview_questions' => array (  0 =>   array (    0 => 'interviewId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\InterviewController::questions',  ),  2 =>   array (    'interviewId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'interviewId',    ),    1 =>     array (      0 => 'text',      1 => '/api/interview/questions',    ),  ),  4 =>   array (  ),),
        'yasoon_site_interview_get_answers' => array (  0 =>   array (    0 => 'questionId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\InterviewController::get_answers',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'questionId',    ),    1 =>     array (      0 => 'text',      1 => '/api/interview/get_answers',    ),  ),  4 =>   array (  ),),
        'yasoon_site_interview_get_interview' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\InterviewController::get_interview',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/interview/get_interviews',    ),  ),  4 =>   array (  ),),
        'yasoon_site_interview_save_interview' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\InterviewController::save_interview',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/interview/save_interview',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_getauthors' => array (  0 =>   array (    0 => 'categoryId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::getAuthorsAction',  ),  2 =>   array (    'categoryId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'categoryId',    ),    1 =>     array (      0 => 'text',      1 => '/api/people/get_authors',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_getpostsbydate' => array (  0 =>   array (    0 => 'categoryId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::getPostsByDateAction',  ),  2 =>   array (    'categoryId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'categoryId',    ),    1 =>     array (      0 => 'text',      1 => '/api/people/get_posts_date',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_getpostsbyrating' => array (  0 =>   array (    0 => 'categoryId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::getPostsByRatingAction',  ),  2 =>   array (    'categoryId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'categoryId',    ),    1 =>     array (      0 => 'text',      1 => '/api/people/get_posts_rating',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_getaboutinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::getAboutInfoAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/people/get_about_info',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_searchpostbydate' => array (  0 =>   array (    0 => 'text',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::searchPostByDateAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'text',    ),    1 =>     array (      0 => 'text',      1 => '/api/people/search_post_by_date',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_searchpostbyrating' => array (  0 =>   array (    0 => 'text',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::searchPostByRatingAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'text',    ),    1 =>     array (      0 => 'text',      1 => '/api/people/search_post_by_rating',    ),  ),  4 =>   array (  ),),
        'yasoon_site_people_searchauthor' => array (  0 =>   array (    0 => 'text',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PeopleController::searchAuthorAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'text',    ),    1 =>     array (      0 => 'text',      1 => '/api/people/search_author',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_savepost' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::savePost',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/savePost',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_add' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::addAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/add',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_update' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::updateAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/update',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_deletepost' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::deletePost',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/deletePost',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_getpost' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getPostAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/getPost',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_getpostsbydate' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getPostsByDate',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/getPostsByDate',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_geteditpost' => array (  0 =>   array (    0 => 'postId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getEditPost',  ),  2 =>   array (    'postId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'postId',    ),    1 =>     array (      0 => 'text',      1 => '/api/post/getEditPost',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_getquestions' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getQuestions',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/getQuestions',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_getstoryoftheday' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getStoryOfTheDayAction',  ),  2 =>   array (    'postId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/get_daystory',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_setstoryoftheday' => array (  0 =>   array (    0 => 'postId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::setStoryOfTheDayAction',  ),  2 =>   array (    'postId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'postId',    ),    1 =>     array (      0 => 'text',      1 => '/api/post/set_daystory',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_like' => array (  0 =>   array (    0 => 'postId',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::like',  ),  2 =>   array (    'postId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'postId',    ),    1 =>     array (      0 => 'text',      1 => '/api/post/like',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_addlikes' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::addLikes',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/add_likes',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_getlastweekposts' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getLastWeekPosts',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/get_all_last_week',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_getbestposts' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::getBestPosts',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/get_best_posts',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_partnerinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::partnerInfo',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/post/partnerInfo',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_get_categoryposts' => array (  0 =>   array (    0 => 'catId',    1 => 'catPage',    2 => 'maxPagePosts',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::get_categoryPosts',  ),  2 =>   array (    'catId' => '\\d+',    'catPage' => '\\d+',    'maxPagePosts' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'maxPagePosts',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'catPage',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'catId',    ),    3 =>     array (      0 => 'text',      1 => '/api/post/get_categoryPosts',    ),  ),  4 =>   array (  ),),
        'yasoon_site_post_get_categorypeople' => array (  0 =>   array (    0 => 'catId',    1 => 'catPage',    2 => 'maxPagePeople',  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\PostController::get_categoryPeople',  ),  2 =>   array (    'catId' => '\\d+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'maxPagePeople',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'catPage',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'catId',    ),    3 =>     array (      0 => 'text',      1 => '/api/post/get_categoryPeople',    ),  ),  4 =>   array (  ),),
        'yasoon_site_question_add' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\QuestionController::addAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/question/add',    ),  ),  4 =>   array (  ),),
        'yasoon_site_question_addinterview' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\QuestionController::addInterviewAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/question/add_interview',    ),  ),  4 =>   array (  ),),
        'yasoon_site_question_setinterviewcaption' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\QuestionController::setInterviewCaption',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/question/set_interview_caption',    ),  ),  4 =>   array (  ),),
        'yasoon_site_question_update' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\QuestionController::updateAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/question/update',    ),  ),  4 =>   array (  ),),
        'yasoon_site_question_remove' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\QuestionController::removeAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/api/question/delete',    ),  ),  4 =>   array (  ),),
        'yasoon_site_socialauth_test' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\SocialAuthController::test',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/socauth/test',    ),  ),  4 =>   array (  ),),
        'yasoon_site_socialauth_testvk' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\SocialAuthController::testvk',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/socauth/vkontakte',    ),  ),  4 =>   array (  ),),
        'yasoon_site_socialauth_testfb' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\SocialAuthController::testfb',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/socauth/facebook',    ),  ),  4 =>   array (  ),),
        'yasoon_site_socialauth_my_tests' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\SocialAuthController::my_tests',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/socauth/my_test',    ),  ),  4 =>   array (  ),),
        'yasoon_site_statistic_getnewusers' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\StatisticController::getNewUsers',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/statistic/getNewUsers',    ),  ),  4 =>   array (  ),),
        'yasoon_site_statistic_getpassusers' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\StatisticController::getPassUsers',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/statistic/getPassUsers',    ),  ),  4 =>   array (  ),),
        'yasoon_site_statistic_getcountusers' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Yasoon\\Site\\Controller\\StatisticController::getCountUsers',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/statistic/getCountUsers',    ),  ),  4 =>   array (  ),),
    );

    /**
     * Constructor.
     */
    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        list($variables, $defaults, $requirements, $tokens, $hostTokens) = self::$declaredRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens);
    }
}
