// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var AuthLoginModel;
  return AuthLoginModel = (function(_super) {

    __extends(AuthLoginModel, _super);

    function AuthLoginModel() {
      return AuthLoginModel.__super__.constructor.apply(this, arguments);
    }

    AuthLoginModel.prototype.name = 'AuthLogin';

    AuthLoginModel.prototype.notify = function(callback) {
      this.method = 'POST';
      this.url = function() {
        return 'api/author/notify';
      };
      this.requestData = {
        email: this.data.email
      };
      return this.request(callback);
    };

    AuthLoginModel.prototype.add = function(callback) {
      return typeof callback === "function" ? callback() : void 0;
    };

    return AuthLoginModel;

  })(Model);
});
