// Generated by CoffeeScript 1.6.1
var IndexView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates_compiled/combined.js'], function(View, template) {});

'use strict';

IndexView = (function(_super) {
  var template;

  __extends(IndexView, _super);

  function IndexView() {
    return IndexView.__super__.constructor.apply(this, arguments);
  }

  IndexView.prototype.autoRender = true;

  IndexView.prototype.className = 'index';

  IndexView.prototype.region = 'main';

  IndexView.prototype.template = template;

  template = null;

  return IndexView;

})(View);
