// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var PostPageView;
  return PostPageView = (function(_super) {

    __extends(PostPageView, _super);

    function PostPageView() {
      return PostPageView.__super__.constructor.apply(this, arguments);
    }

    PostPageView.prototype.autoRender = true;

    PostPageView.prototype.className = 'postPage';

    PostPageView.prototype.container = '#center';

    PostPageView.prototype.regions = {
      '#post': 'post',
      '#newQuestion': 'newQuestion',
      '#questionsQueue': 'questionsQueue'
    };

    PostPageView.prototype.templateName = 'postPage';

    return PostPageView;

  })(View);
});
