// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/pagingQueue', 'models/admin/timeline/post'], function(PagingQueue, PostModel) {
  'use strict';
  var AdminTimelinePostQueueModel;
  return AdminTimelinePostQueueModel = (function(_super) {

    __extends(AdminTimelinePostQueueModel, _super);

    function AdminTimelinePostQueueModel() {
      return AdminTimelinePostQueueModel.__super__.constructor.apply(this, arguments);
    }

    AdminTimelinePostQueueModel.prototype.name = 'AdminTimelinePostQueue';

    AdminTimelinePostQueueModel.prototype.elementName = 'AdminTimelinePost';

    AdminTimelinePostQueueModel.prototype.paging = true;

    AdminTimelinePostQueueModel.prototype.stackUrl = function() {
      return 'api/friends/admin_timeline_stack';
    };

    AdminTimelinePostQueueModel.prototype.loadUrl = function() {
      return 'api/friends/timeline';
    };

    AdminTimelinePostQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new PostModel();
      model.data = elData;
      return model;
    };

    return AdminTimelinePostQueueModel;

  })(PagingQueue);
});
