// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var AdminTimelinePostModel;
  return AdminTimelinePostModel = (function(_super) {

    __extends(AdminTimelinePostModel, _super);

    function AdminTimelinePostModel() {
      return AdminTimelinePostModel.__super__.constructor.apply(this, arguments);
    }

    AdminTimelinePostModel.prototype.name = 'TimelinePost';

    AdminTimelinePostModel.prototype.setChecked = function(callback) {
      console.log('set checked');
      return typeof callback === "function" ? callback() : void 0;
    };

    return AdminTimelinePostModel;

  })(Model);
});
