// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/people/author'], function(QueueView, JST, AuthorView) {
  'use strict';
  var PeopleAuthorQueueView;
  return PeopleAuthorQueueView = (function(_super) {

    __extends(PeopleAuthorQueueView, _super);

    function PeopleAuthorQueueView() {
      return PeopleAuthorQueueView.__super__.constructor.apply(this, arguments);
    }

    PeopleAuthorQueueView.prototype.className = 'PeopleAuthorQueue';

    PeopleAuthorQueueView.prototype.templateName = 'people_author_queue';

    PeopleAuthorQueueView.prototype.sortable = true;

    PeopleAuthorQueueView.prototype.createElementView = function(model) {
      return new AuthorView({
        model: model
      });
    };

    return PeopleAuthorQueueView;

  })(QueueView);
});
