// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var PeopleAuthorView, _ref;
  return PeopleAuthorView = (function(_super) {
    __extends(PeopleAuthorView, _super);

    function PeopleAuthorView() {
      _ref = PeopleAuthorView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PeopleAuthorView.prototype.className = 'author';

    PeopleAuthorView.prototype.templateName = 'people_author';

    return PeopleAuthorView;

  })(View);
});
