// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'JST'], function(View, JST) {
  'use strict';
  var PeopleHeaderView;
  return PeopleHeaderView = (function(_super) {

    __extends(PeopleHeaderView, _super);

    function PeopleHeaderView() {
      return PeopleHeaderView.__super__.constructor.apply(this, arguments);
    }

    PeopleHeaderView.prototype.autoRender = true;

    PeopleHeaderView.prototype.className = 'inside';

    PeopleHeaderView.prototype.region = 'header';

    PeopleHeaderView.prototype.templateName = 'people_header';

    PeopleHeaderView.prototype.initialize = function(params) {
      this.categoryId = params.catId;
      if (params.mode) {
        return this.mode = params.mode;
      } else {
        return this.mode = 'date';
      }
    };

    PeopleHeaderView.prototype.getTemplateData = function() {
      return {
        catId: this.categoryId,
        mode: this.mode
      };
    };

    return PeopleHeaderView;

  })(View);
});
