// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/page', 'JST', 'views/common/footer', 'views/author/posts/header', 'categories'], function(PageView, JST, FooterView, HeaderView, categories) {
  'use strict';
  var PeoplePageView,
    _this = this;
  return PeoplePageView = (function(_super) {

    __extends(PeoplePageView, _super);

    function PeoplePageView() {
      var _this = this;
      this.setActiveCategory = function(id) {
        return PeoplePageView.prototype.setActiveCategory.apply(_this, arguments);
      };
      return PeoplePageView.__super__.constructor.apply(this, arguments);
    }

    PeoplePageView.prototype.className = 'peoplePage';

    PeoplePageView.prototype.regions = {
      '#queue': 'queue',
      'footer': 'footer',
      'header': 'header'
    };

    PeoplePageView.prototype.templateName = 'people_page';

    PeoplePageView.prototype.setActiveCategory = function(id) {
      this.activeCategoryId = id;
      return this.activeCategory = categories[this.activeCategoryId];
    };

    PeoplePageView.prototype.initialize = function() {
      PeoplePageView.__super__.initialize.apply(this, arguments);
      return this.setActiveCategory(1);
    };

    PeoplePageView.prototype.events = {
      'click .category': function(e) {
        var target;
        target = $(e.target);
        target.parent().find('.category').each(function() {
          return $(this).removeClass('active');
        });
        target.addClass('active');
        this.setActiveCategory(target.attr('id'));
        return this.render();
      }
    };

    PeoplePageView.prototype.render = function() {
      var fv, hv;
      PeoplePageView.__super__.render.apply(this, arguments);
      hv = new HeaderView();
      return fv = new FooterView();
    };

    PeoplePageView.prototype.getTemplateData = function() {
      console.log(this.activeCategoryId);
      return {
        categories: categories,
        activeCategory: this.activeCategory,
        activeCatId: this.activeCategoryId
      };
    };

    return PeoplePageView;

  })(PageView);
});
