// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AuthorPostBlankQuestionView;
  return AuthorPostBlankQuestionView = (function(_super) {

    __extends(AuthorPostBlankQuestionView, _super);

    function AuthorPostBlankQuestionView() {
      return AuthorPostBlankQuestionView.__super__.constructor.apply(this, arguments);
    }

    AuthorPostBlankQuestionView.prototype.className = 'author_post_blank_question';

    AuthorPostBlankQuestionView.prototype.templateName = 'author_post_blank_question';

    AuthorPostBlankQuestionView.prototype.modes = ['button', 'passive', 'active', 'preview'];

    return AuthorPostBlankQuestionView;

  })(EditableView);
});
