// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['models/base/queue', 'models/author/posts/post'], function(Queue, PostModel) {
  'use strict';
  var AuthorPostsPostQueueModel;
  return AuthorPostsPostQueueModel = (function(_super) {

    __extends(AuthorPostsPostQueueModel, _super);

    function AuthorPostsPostQueueModel() {
      return AuthorPostsPostQueueModel.__super__.constructor.apply(this, arguments);
    }

    AuthorPostsPostQueueModel.prototype.name = 'AuthorPostsPostQueue';

    AuthorPostsPostQueueModel.prototype.elementName = 'AuthorPostsPost';

    AuthorPostsPostQueueModel.prototype.initialize = function(params) {
      AuthorPostsPostQueueModel.__super__.initialize.apply(this, arguments);
      return this.authorId = params.authorId;
    };

    AuthorPostsPostQueueModel.prototype.load = function(callback) {
      this.url = function() {
        return 'api/author/get_posts/' + this.authorId;
      };
      this.method = 'GET';
      return AuthorPostsPostQueueModel.__super__.load.call(this, callback);
    };

    AuthorPostsPostQueueModel.prototype.updatePlaces = function(callback) {
      this.url = function() {
        return 'api/author/update_posts_places/' + this.authorId;
      };
      this.method = 'POST';
      return AuthorPostsPostQueueModel.__super__.updatePlaces.call(this, callback);
    };

    AuthorPostsPostQueueModel.prototype.createElementModel = function(elData) {
      var model;
      model = new PostModel({
        authorId: elData.authorId
      });
      model.data = elData;
      return model;
    };

    return AuthorPostsPostQueueModel;

  })(Queue);
});
