// Generated by CoffeeScript 1.6.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/editable', 'JST'], function(EditableView, JST) {
  'use strict';
  var AdminContentRowView;
  return AdminContentRowView = (function(_super) {

    __extends(AdminContentRowView, _super);

    function AdminContentRowView() {
      return AdminContentRowView.__super__.constructor.apply(this, arguments);
    }

    AdminContentRowView.prototype.className = 'row';

    AdminContentRowView.prototype.templateName = 'admin_content_row';

    AdminContentRowView.prototype.modes = ['passive', 'active'];

    AdminContentRowView.prototype.updateCallback = function() {
      return this.setMode('passive');
    };

    return AdminContentRowView;

  })(EditableView);
});
