// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/queue', 'JST', 'views/admin/content/row'], function(QueueView, JST, RowView) {
  'use strict';
  var AdminContentRowQueueView, _ref;
  return AdminContentRowQueueView = (function(_super) {
    __extends(AdminContentRowQueueView, _super);

    function AdminContentRowQueueView() {
      _ref = AdminContentRowQueueView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AdminContentRowQueueView.prototype.className = 'rowQueue';

    AdminContentRowQueueView.prototype.templateName = 'admin_content_row_queue';

    AdminContentRowQueueView.prototype.sortable = false;

    AdminContentRowQueueView.prototype.createElementView = function(model) {
      return new RowView({
        model: model
      });
    };

    return AdminContentRowQueueView;

  })(QueueView);
});
